#############################################################################
# Makefile for building: Sky_Is_Falling
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu May 9 10:58:06 2013
# Project:  Sky_Is_Falling.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Sky_Is_Falling.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = animal.cpp \
		cheetah.cpp \
		donkey.cpp \
		farmer.cpp \
		fox.cpp \
		gazelle.cpp \
		main.cpp \
		mainwindow.cpp \
		rabbit.cpp \
		turtle.cpp \
		wolf.cpp moc_mainwindow.cpp
OBJECTS       = animal.o \
		cheetah.o \
		donkey.o \
		farmer.o \
		fox.o \
		gazelle.o \
		main.o \
		mainwindow.o \
		rabbit.o \
		turtle.o \
		wolf.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Sky_Is_Falling.pro
QMAKE_TARGET  = Sky_Is_Falling
DESTDIR       = 
TARGET        = Sky_Is_Falling

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Sky_Is_Falling.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Sky_Is_Falling.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Sky_Is_Falling.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Sky_Is_Falling1.0.0 || $(MKDIR) .tmp/Sky_Is_Falling1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Sky_Is_Falling1.0.0/ && $(COPY_FILE) --parents animal.h cheetah.h donkey.h farmer.h fox.h gazelle.h mainwindow.h rabbit.h turtle.h wolf.h .tmp/Sky_Is_Falling1.0.0/ && $(COPY_FILE) --parents animal.cpp cheetah.cpp donkey.cpp farmer.cpp fox.cpp gazelle.cpp main.cpp mainwindow.cpp rabbit.cpp turtle.cpp wolf.cpp .tmp/Sky_Is_Falling1.0.0/ && (cd `dirname .tmp/Sky_Is_Falling1.0.0` && $(TAR) Sky_Is_Falling1.0.0.tar Sky_Is_Falling1.0.0 && $(COMPRESS) Sky_Is_Falling1.0.0.tar) && $(MOVE) `dirname .tmp/Sky_Is_Falling1.0.0`/Sky_Is_Falling1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Sky_Is_Falling1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: farmer.h \
		animal.h \
		turtle.h \
		donkey.h \
		fox.h \
		gazelle.h \
		cheetah.h \
		rabbit.h \
		wolf.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

animal.o: animal.cpp animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animal.o animal.cpp

cheetah.o: cheetah.cpp cheetah.h \
		animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cheetah.o cheetah.cpp

donkey.o: donkey.cpp donkey.h \
		animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o donkey.o donkey.cpp

farmer.o: farmer.cpp farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o farmer.o farmer.cpp

fox.o: fox.cpp fox.h \
		animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fox.o fox.cpp

gazelle.o: gazelle.cpp gazelle.h \
		animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gazelle.o gazelle.cpp

main.o: main.cpp mainwindow.h \
		farmer.h \
		animal.h \
		turtle.h \
		donkey.h \
		fox.h \
		gazelle.h \
		cheetah.h \
		rabbit.h \
		wolf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		farmer.h \
		animal.h \
		turtle.h \
		donkey.h \
		fox.h \
		gazelle.h \
		cheetah.h \
		rabbit.h \
		wolf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

rabbit.o: rabbit.cpp rabbit.h \
		animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rabbit.o rabbit.cpp

turtle.o: turtle.cpp turtle.h \
		animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o turtle.o turtle.cpp

wolf.o: wolf.cpp wolf.h \
		animal.h \
		farmer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wolf.o wolf.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

